-- Cambio 2026-09-30 (DEC-37) para bases creadas antes: se ejecuta una sola vez y conserva los datos
BEGIN;
SET LOCAL search_path TO "KomainOS";

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'KomainOS' AND table_name = 'servidor' AND column_name = 'direccion_ip') THEN
        RAISE EXCEPTION 'El cambio ya fue aplicado en esta base (servidor.direccion_ip no existe)';
    END IF;
END $$;

ALTER TABLE servidor RENAME COLUMN datacenter TO vdc;

ALTER TABLE servidor
    ADD COLUMN cantidad_cpu integer,
    ADD COLUMN ram_gb numeric(7,2),
    ADD COLUMN hd_virtual_gb numeric(10,2),
    ADD CONSTRAINT ck_servidor_recursos CHECK ((((cantidad_cpu IS NULL) OR (cantidad_cpu > 0)) AND ((ram_gb IS NULL) OR (ram_gb > (0)::numeric)) AND ((hd_virtual_gb IS NULL) OR (hd_virtual_gb > (0)::numeric))));

CREATE TABLE direccion_ip (
    id_direccion_ip integer NOT NULL,
    id_servidor integer NOT NULL,
    direccion character varying(45) NOT NULL,
    principal boolean DEFAULT false NOT NULL
);
ALTER TABLE direccion_ip ALTER COLUMN id_direccion_ip ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "KomainOS".direccion_ip_id_direccion_ip_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY direccion_ip
    ADD CONSTRAINT direccion_ip_pkey PRIMARY KEY (id_direccion_ip);
ALTER TABLE ONLY direccion_ip
    ADD CONSTRAINT uq_direccion_ip_direccion UNIQUE (direccion);
ALTER TABLE ONLY direccion_ip
    ADD CONSTRAINT ex_direccion_ip_principal EXCLUDE USING btree (id_servidor WITH =) WHERE (principal) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY direccion_ip
    ADD CONSTRAINT fk_direccion_ip_servidor FOREIGN KEY (id_servidor) REFERENCES servidor(id_servidor) ON UPDATE RESTRICT ON DELETE CASCADE;

-- La IP que ya tenía cada servidor pasa a ser su IP principal
INSERT INTO direccion_ip (id_servidor, direccion, principal)
SELECT id_servidor, direccion_ip, true FROM servidor;

ALTER TABLE servidor DROP CONSTRAINT uq_servidor_direccion_ip;
ALTER TABLE servidor DROP COLUMN direccion_ip;

COMMIT;
